export const SEARCH_SETUP_START = "SEARCH_SETUP_START";
export const SEARCH_SETUP = "SEARCH_SETUP";
export const SEARCH_SETUP_SUCCESS = "SEARCH_SETUP_SUCCESS";
export const SEARCH_SETUP_FAIL = "SEARCH_SETUP_FAIL";